spring:
  jmx:
    enabled: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  #    publisher-confirm-type: CORRELATED
  #    publisher-returns: true
  cloud:
    bus:
      destination: SPRING_MESSAGE_BUS
    stream:
      # 声明消费者通道，一般来说使用3.0后的spring cloud stream 可用通过实现Consumer接口来自动注册通道
      # 我们这里显式声明的原因是期望通过这样的配置，使得IntegrationFlow能直接读取到通道中来自MQ的消息，而不需要经过网关
      input-bindings: amqpMessage
      bindings:
#        amqpMessage-in-0:
        AMQP_MESSAGE_INPUT:
          destination: AMQP_DESTINATION
          group: AMQP_INPUT
        #        TEMP_INPUT:
        #          destination: TEMP_INPUT
        #          group: TEMP_IN
        AMQP_MESSAGE_OUTPUT:
          destination: AMQP_DESTINATION
        springCloudBusInput:
          destination: SPRING_MESSAGE_BUS
          group: SPRING_MESSAGE
      function:
        bindings:
          amqpMessage-in-0: AMQP_MESSAGE_INPUT
          #          temp-in-0: TEMP_INPUT
          amqpMessage-out-0: AMQP_MESSAGE_OUTPUT
      # 声明一个输出通道，该用输出通道提供给gateway使用，从而发送消息，减少对业务代码的侵入
      output-bindings: amqpMessage
      rabbit:
        bindings:
          AMQP_MESSAGE_OUTPUT:
            producer:
              routing-key-expression: ''''''
          TEMP_INPUT:
            consumer:
              queueName-group-only: true
              binding-routing-key: temp.#
#    function:
#      definition: temp

logging:
  level:
    root: debug
